# coding: utf-8

"""
    AI-Assisted Content Moderation & Publishing API

    Backend service for drafting, reviewing, and publishing blog posts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moderation_sdk.models.post_status import PostStatus

class TestPostStatus(unittest.TestCase):
    """PostStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostStatus(self):
        """Test PostStatus"""
        # inst = PostStatus()

if __name__ == '__main__':
    unittest.main()
