# coding: utf-8

"""
    AI-Assisted Content Moderation & Publishing API

    Backend service for drafting, reviewing, and publishing blog posts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moderation_sdk.models.status_count import StatusCount

class TestStatusCount(unittest.TestCase):
    """StatusCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusCount:
        """Test StatusCount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusCount`
        """
        model = StatusCount()
        if include_optional:
            return StatusCount(
                status = '',
                count = 56
            )
        else:
            return StatusCount(
                status = '',
                count = 56,
        )
        """

    def testStatusCount(self):
        """Test StatusCount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
