# coding: utf-8

"""
    AI-Assisted Content Moderation & Publishing API

    Backend service for drafting, reviewing, and publishing blog posts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from moderation_sdk.models.stats_response import StatsResponse

class TestStatsResponse(unittest.TestCase):
    """StatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsResponse:
        """Test StatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsResponse`
        """
        model = StatsResponse()
        if include_optional:
            return StatsResponse(
                status_distribution = [
                    moderation_sdk.models.status_count.StatusCount(
                        status = '', 
                        count = 56, )
                    ],
                timeline = [
                    moderation_sdk.models.timeline_entry.TimelineEntry(
                        date = '', 
                        count = 56, )
                    ],
                top_flagged_reasons = [
                    moderation_sdk.models.reason_count.ReasonCount(
                        reason = '', 
                        count = 56, )
                    ],
                total_posts = 56,
                approval_rate = 1.337,
                flag_rate = 1.337
            )
        else:
            return StatsResponse(
                status_distribution = [
                    moderation_sdk.models.status_count.StatusCount(
                        status = '', 
                        count = 56, )
                    ],
                timeline = [
                    moderation_sdk.models.timeline_entry.TimelineEntry(
                        date = '', 
                        count = 56, )
                    ],
                top_flagged_reasons = [
                    moderation_sdk.models.reason_count.ReasonCount(
                        reason = '', 
                        count = 56, )
                    ],
                total_posts = 56,
                approval_rate = 1.337,
                flag_rate = 1.337,
        )
        """

    def testStatsResponse(self):
        """Test StatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
