# coding: utf-8

"""
    AI-Assisted Content Moderation & Publishing API

    Backend service for drafting, reviewing, and publishing blog posts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PostStatus(str, Enum):
    """
    PostStatus
    """

    """
    allowed enum values
    """
    DRAFT = 'draft'
    FLAGGED = 'flagged'
    APPROVED = 'approved'
    PUBLISHED = 'published'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PostStatus from a JSON string"""
        return cls(json.loads(json_str))


